//For dropdown
export const entityTypeOptions = [
  { value: "ADF", label: "Approved Deposit Fund" },
  { value: "ARF", label: "Ancillary Reform Fund" },
  { value: "COP", label: "Cooperative" },
  { value: "CUT", label: "Corporate Unit Trust" },
  { value: "DES", label: "Deceased Estate" },
  { value: "DIP", label: "Diplomatic / Consulate Body" },
  { value: "FGA", label: "Foreign Government Agency" },
  { value: "FGD", label: "Foreign Government Department" },
  { value: "FHS", label: "First Home Saver Account" },
  { value: "FPT", label: "Family Partnership" },
  { value: "FSA", label: "Farm Management Account" },
  { value: "GOV", label: "Government Entity" },
  { value: "IND", label: "Individual / Sole Trader" },
  { value: "JVT", label: "Joint Venture" },
  { value: "LOC", label: "Local Government Entity" },
  { value: "LPT", label: "Limited Partnership" },
  { value: "NRF", label: "Non-Resident Fund" },
  { value: "OIE", label: "Other Incorporated Entity" },
  { value: "PDF", label: "Pooled Development Fund" },
  { value: "PRV", label: "Australian Private Company" },
  { value: "PST", label: "Pooled Superannuation Trust" },
  { value: "PTR", label: "Partnership" },
  { value: "PTT", label: "Public Unit Trust" },
  { value: "PUB", label: "Australian Public Company" },
  { value: "SMF", label: "Self-Managed Superannuation Fund" },
  { value: "SSA", label: "Sector Superannuation Account" },
  { value: "STA", label: "State Government Entity" },
  { value: "STR", label: "Strata Title" },
  { value: "SUP", label: "Superannuation Fund" },
  { value: "TER", label: "Territory Government Entity" },
  { value: "TRT", label: "Trust" },
  { value: "UIE", label: "Unincorporated Entity" },
  { value: "CGT", label: "Commonwealth Government Trust" },
  { value: "LGA", label: "Local Government Agency" },
  { value: "LGC", label: "Local Government Corporation" },
  { value: "LGE", label: "Local Government Entity" },
  { value: "LGP", label: "Local Government Partnership" },
  { value: "LGS", label: "Local Government Statutory Body" },
  { value: "LGT", label: "Local Government Trust" },
  { value: "SGA", label: "State Government Agency" },
  { value: "SGC", label: "State Government Corporation" },
  { value: "SGE", label: "State Government Entity" },
  { value: "SGP", label: "State Government Partnership" },
  { value: "SGS", label: "State Government Statutory Body" },
  { value: "SGT", label: "State Government Trust" },
  { value: "TGA", label: "Territory Government Agency" },
  { value: "TGC", label: "Territory Government Corporation" },
  { value: "TGE", label: "Territory Government Entity" },
  { value: "TGP", label: "Territory Government Partnership" },
  { value: "TGS", label: "Territory Government Statutory Body" },
  { value: "TGT", label: "Territory Government Trust" },
  { value: "CGA", label: "Commonwealth Government Agency" },
  { value: "CGC", label: "Commonwealth Government Corporation" },
  { value: "CGE", label: "Commonwealth Government Entity" },
  { value: "CGP", label: "Commonwealth Government Partnership" },
  { value: "CGS", label: "Commonwealth Government Statutory Body" },
  { value: "CMT", label: "Cash Management Trust" },
  { value: "CSA", label: "Commonwealth Statutory Authority" },
  { value: "CSP", label: "Commonwealth Statutory Partnership" },
  { value: "CSS", label: "Commonwealth Statutory Superannuation" },
  { value: "CTC", label: "Commonwealth Trust - Charitable" },
  { value: "CTD", label: "Commonwealth Trust - Discretionary" },
  { value: "CTF", label: "Commonwealth Trust - Fixed" },
  { value: "CTH", label: "Commonwealth Trust - Hybrid" },
  { value: "CTI", label: "Commonwealth Trust - Investment" },
  { value: "CTL", label: "Commonwealth Trust - Listed" },
  { value: "CTQ", label: "Commonwealth Trust - Public" },
  { value: "CTT", label: "Commonwealth Trust - Trading" },
  { value: "CTU", label: "Commonwealth Trust - Unit" },
  { value: "DIT", label: "Discretionary Investment Trust" },
  { value: "DST", label: "Discretionary Services Trust" },
  { value: "DTT", label: "Discretionary Trading Trust" },
  { value: "FUT", label: "Fixed Unit Trust" },
  { value: "FXT", label: "Fixed Trust" },
  { value: "HYT", label: "Hybrid Trust" },
  { value: "LSA", label: "Local Statutory Authority" },
  { value: "LSP", label: "Local Statutory Partnership" },
  { value: "LSS", label: "Local Statutory Superannuation" },
  { value: "NPF", label: "Non-profit Fund" },
  { value: "POF", label: "Public Offering Fund" },
  { value: "PQT", label: "Public Quality Trust" },
  { value: "PUT", label: "Public Unit Trust" },
  { value: "SAF", label: "Small APRA Fund" },
  { value: "SSP", label: "State Statutory Partnership" },
  { value: "SSS", label: "State Statutory Superannuation" },
  { value: "TSA", label: "Territory Statutory Authority" },
  { value: "TSP", label: "Territory Statutory Partnership" },
  { value: "TSS", label: "Territory Statutory Superannuation" },
  { value: "CSF", label: "Corporate Superannuation Fund" },
];

//To use in table
export const entityTypeLabelMap = Object.fromEntries(
  entityTypeOptions.map((o) => [o.value, o.label])
);
