//For dropdown
export const entityTypeOptions = [
  { label: "Australian Defence Force", value: "ADF" },
  { label: "Aboriginal Corporation Registered", value: "ARF" },
  { label: "Company (Other Private)", value: "COP" },
  { label: "Company Unlimited", value: "CUT" },
  { label: "Designated Entity", value: "DES" },
  { label: "Discretionary Investment Partnership", value: "DIP" },
  { label: "Foreign Government Agency", value: "FGA" },
  { label: "Foreign Government Department", value: "FGD" },
  { label: "Foreign High School", value: "FHS" },
  { label: "Foreign Proprietary Trust", value: "FPT" },
  { label: "Foreign Superannuation Fund", value: "FSA" },
  { label: "Government Entity", value: "GOV" },
  { label: "Individual / Sole Trader", value: "IND" },
  { label: "Joint Venture Trust", value: "JVT" },
  { label: "Local Authority", value: "LOC" },
  { label: "Limited Partnership Trust", value: "LPT" },
  { label: "Non-Reporting Foreign Entity", value: "NRF" },
  { label: "Other Incorporated Entity", value: "OIE" },
  { label: "Publicly Funded Department", value: "PDF" },
  { label: "Private Company", value: "PRV" },
  { label: "Post Secondary Institution", value: "PST" },
  { label: "Partnership", value: "PTR" },
  { label: "Public Trust", value: "PTT" },
  { label: "Australian Public Company", value: "PUB" },
  { label: "Small Fund", value: "SMF" },
  { label: "State Authority", value: "SSA" },
  { label: "State Agency", value: "STA" },
  { label: "State Trust", value: "STR" },
  { label: "Superannuation Fund", value: "SUP" },
  { label: "Territory Authority", value: "TER" },
  { label: "Trust", value: "TRT" },
  { label: "Unincorporated Entity", value: "UIE" },
  { label: "Commonwealth Government Agency", value: "CGT" },
  { label: "Local Government Authority", value: "LGA" },
  { label: "Local Government Council", value: "LGC" },
  { label: "Local Government Entity", value: "LGE" },
  { label: "Local Government Partnership", value: "LGP" },
  { label: "Local Government Service", value: "LGS" },
  { label: "Local Government Trust", value: "LGT" },
  { label: "State Government Agency", value: "SGA" },
  { label: "State Government Council", value: "SGC" },
  { label: "State Government Entity", value: "SGE" },
  { label: "State Government Partnership", value: "SGP" },
  { label: "State Government Service", value: "SGS" },
  { label: "State Government Trust", value: "SGT" },
  { label: "Territory Government Agency", value: "TGA" },
  { label: "Territory Government Council", value: "TGC" },
  { label: "Territory Government Entity", value: "TGE" },
  { label: "Territory Government Partnership", value: "TGP" },
  { label: "Territory Government Service", value: "TGS" },
  { label: "Territory Government Trust", value: "TGT" },
  { label: "Commonwealth Government Agency", value: "CGA" },
  { label: "Commonwealth Government Council", value: "CGC" },
  { label: "Commonwealth Government Entity", value: "CGE" },
  { label: "Commonwealth Government Partnership", value: "CGP" },
  { label: "Commonwealth Government Service", value: "CGS" },
  { label: "Commonwealth Government Board", value: "CCB" },
  { label: "Commonwealth Government Commission", value: "CCC" },
  { label: "Commonwealth Government Local Body", value: "CCL" },
  { label: "Commonwealth Government Network", value: "CCN" },
  { label: "Commonwealth Government Organization", value: "CCO" },
  { label: "Commonwealth Government Program", value: "CCP" },
  { label: "Commonwealth Government Region", value: "CCR" },
  { label: "Commonwealth Government Service", value: "CCS" },
  { label: "Commonwealth Government Trust", value: "CCT" },
  { label: "Commonwealth Government Union", value: "CCU" },
  { label: "Community Trust", value: "CMT" },
  { label: "Community Service Agency", value: "CSA" },
  { label: "Community Service Program", value: "CSP" },
  { label: "Community Service Service", value: "CSS" },
  { label: "Catholic Trust Council", value: "CTC" },
  { label: "Catholic Trust Department", value: "CTD" },
  { label: "Catholic Trust Fund", value: "CTF" },
  { label: "Catholic Trust High School", value: "CTH" },
  { label: "Catholic Trust Institute", value: "CTI" },
  { label: "Catholic Trust Local Body", value: "CTL" },
  { label: "Catholic Trust Query", value: "CTQ" },
  { label: "Catholic Trust Trust", value: "CTT" },
  { label: "Catholic Trust Union", value: "CTU" },
  { label: "Discretionary Investment Trust", value: "DIT" },
  { label: "Discretionary Service Trust", value: "DST" },
  { label: "Discretionary Trust", value: "DTT" },
  { label: "Foreign Unit Trust", value: "FUT" },
  { label: "Foreign Exchange Trust", value: "FXT" },
  { label: "Hybrid Trust", value: "HYT" },
  { label: "Local Cooperative Body", value: "LCB" },
  { label: "Local Cooperative Council", value: "LCC" },
  { label: "Local Cooperative Local Body", value: "LCL" },
  { label: "Local Cooperative Network", value: "LCN" },
  { label: "Local Cooperative Organization", value: "LCO" },
  { label: "Local Cooperative Program", value: "LCP" },
  { label: "Local Cooperative Region", value: "LCR" },
  { label: "Local Cooperative Service", value: "LCS" },
  { label: "Local Cooperative Trust", value: "LCT" },
  { label: "Local Cooperative Union", value: "LCU" },
  { label: "Local Service Agency", value: "LSA" },
  { label: "Local Service Program", value: "LSP" },
  { label: "Local Service Service", value: "LSS" },
  { label: "Local Trust Council", value: "LTC" },
  { label: "Limited Trust Department", value: "LTD" },
  { label: "Limited Trust Fund", value: "LTF" },
  { label: "Limited Trust High School", value: "LTH" },
  { label: "Limited Trust Institute", value: "LTI" },
  { label: "Limited Trust Local Body", value: "LTL" },
  { label: "Limited Trust Query", value: "LTQ" },
  { label: "Limited Trust Trust", value: "LTT" },
  { label: "Limited Trust Union", value: "LTU" },
  { label: "Not-for-profit Foundation", value: "NPF" },
  { label: "Public Offer Foundation", value: "POF" },
  { label: "Public Query Trust", value: "PQT" },
  { label: "Public Unit Trust", value: "PUT" },
  { label: "Safety Fund", value: "SAF" },
  { label: "School Community Board", value: "SCB" },
  { label: "School Community Council", value: "SCC" },
  { label: "School Community Local Body", value: "SCL" },
  { label: "School Community Network", value: "SCN" },
  { label: "School Community Organization", value: "SCO" },
  { label: "School Community Program", value: "SCP" },
  { label: "School Community Region", value: "SCR" },
  { label: "School Community Service", value: "SCS" },
  { label: "School Community Trust", value: "SCT" },
  { label: "School Community Union", value: "SCU" },
  { label: "State Service Program", value: "SSP" },
  { label: "State Service Service", value: "SSS" },
  { label: "State Trust Council", value: "STC" },
  { label: "State Trust Department", value: "STD" },
  { label: "State Trust Fund", value: "STF" },
  { label: "State Trust High School", value: "STH" },
  { label: "State Trust Institute", value: "STI" },
  { label: "State Trust Local Body", value: "STL" },
  { label: "State Trust Query", value: "STQ" },
  { label: "State Trust Trust", value: "STT" },
  { label: "State Trust Union", value: "STU" },
  { label: "Territory Community Board", value: "TCB" },
  { label: "Territory Community Council", value: "TCC" },
  { label: "Territory Community Local Body", value: "TCL" },
  { label: "Territory Community Network", value: "TCN" },
  { label: "Territory Community Organization", value: "TCO" },
  { label: "Territory Community Program", value: "TCP" },
  { label: "Territory Community Region", value: "TCR" },
  { label: "Territory Community Service", value: "TCS" },
  { label: "Territory Community Trust", value: "TCT" },
  { label: "Territory Community Union", value: "TCU" },
  { label: "Territory Service Agency", value: "TSA" },
  { label: "Territory Service Program", value: "TSP" },
  { label: "Territory Service Service", value: "TSS" },
  { label: "Territory Trust Council", value: "TTC" },
  { label: "Territory Trust Department", value: "TTD" },
  { label: "Territory Trust Fund", value: "TTF" },
  { label: "Territory Trust High School", value: "TTH" },
  { label: "Territory Trust Institute", value: "TTI" },
  { label: "Territory Trust Local Body", value: "TTL" },
  { label: "Territory Trust Query", value: "TTQ" },
  { label: "Territory Trust Trust", value: "TTT" },
  { label: "Territory Trust Union", value: "TTU" },
  { label: "Community Service Fund", value: "CSF" },
];

//To use in table
export const entityTypeLabelMap = Object.fromEntries(
  entityTypeOptions.map((o) => [o.value, o.label])
);
